### ISSUE TITLE
Non-zero error code 9 of `groupadd` command inside `GitBugJavaCli.__setup_base_image()` during build

### ISSUE THREAD

**Issue by Vladislav0Art** [gitbugactions/gitbug-java#18] opened 2024-03-04 19:38 UTC
## Description of the problem
I am trying to run the `setup` command of the package, i.e. run the following (executing on a virtual machine):
```bash
# not 'gitbug-java setup' because in the VM the elevated privileges of sudo required
sudo ./venv/bin/python gitbug-java setup
``` 
But after downloading of the docker image the execution fails with following stack trace:
```
(venv) ubuntu@ip-172-31-14-68:~/projects/gitbug-java$ sudo ./venv/bin/python gitbug-java setup
Traceback (most recent call last):
  File "/home/ubuntu/projects/gitbug-java/gitbug-java", line 206, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/projects/gitbug-java/gitbug-java", line 202, in main
    fire.Fire(GitBugJavaCli)
  File "/home/ubuntu/projects/gitbug-java/venv/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/gitbug-java/venv/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/gitbug-java/venv/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/gitbug-java/gitbug-java", line 185, in setup
    self.__setup_base_image()
  File "/home/ubuntu/projects/gitbug-java/gitbug-java", line 68, in __setup_base_image
    client.images.build(path=tmp_dir, tag=runner_image, forcerm=True)
  File "/home/ubuntu/projects/gitbug-java/venv/lib/python3.11/site-packages/docker/models/images.py", line 285, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: The command '/bin/sh -c sudo groupadd -o -g 0 root' returned a non-zero code: 9
```

## Expected behavior
The setup command should run smoothly with no errors.

## The environment

The exact commands I have executed prior the `gitbug-java setup`:
```bash
# should be an analogy to `poetry shell`
python3.11 -m venv ./venv
# enter virtual env
. ./venv/bin/activate
poetry install --no-root
export PATH="$(pwd):$(pwd)/bin:$PATH"
sudo ./venv/bin/python gitbug-java setup # this fails
```

1. Python version: `Python 3.11.0rc1`
2. Docker version: `Docker version 25.0.3, build 4debf41`
3. Poetry version: `Poetry (version 1.8.2)`
4. System:
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
```

**The exact same error occurs for mac with the following parameters:**
(For the mac I made the setup via `poetry shell`)
1. Docker: `Docker version 25.0.3, build 4debf41`
2. Python: `Python 3.11.8`
3. Poetry: `Poetry (version 1.8.1)`
4. System:
```
Macbook Pro 2019, Intel
macOS Sonoma, Version 14.2.1
```

**Comment by Vladislav0Art** [comment] 2024-03-04 19:39
Could you please provide the versions of the aforementioned utilities on which the `gitbug-java setup` succeeds?

**Comment by Nfsaavedra** [comment] 2024-03-04 21:46
Hi!

I was able to replicate the issue you found by following the provided commands. The issue is related to the usage of `sudo` since when I removed the `sudo`, I was able to run the command successfully.

The problem is that we collect the UID and GID of the user that is running the program, and when `sudo` is used, both the UID and GID are 0. We set the user `runner` inside the container to the same UID and GID of the user running outside the container. We do this so the permissions of the report files for the tests have the correct permissions. We mount the local repository where a bug was found on the container and then we run the tests there. Since the container uses the `runner` user, if the UID and GID are different from the user "outside the container", the generated reports would have permissions that do not allow us to access them outside.

Now, the problem with using sudo is that the user `root` exists inside the container. So, when we try to change the UID and GID of the user `runner`, the system does not allow that. We could probably get the UID and GID of the actual user instead of 0 when using `sudo` (for instance, by using the `SUDO_USER` env variable), but the problem that `gitbug-java` would need to be run without the `sudo` (after the setup phase) would (probably?) remain.

Nonetheless, we can try that if you **really** need to use sudo.

**Comment by Vladislav0Art** [comment] 2024-03-06 14:26
Hello! Sorry for the delayed reply. 

I [realized](https://stackoverflow.com/a/68897084) that I need to add my current user to the `docker` group:
```
sudo usermod -aG docker $USER
```
Now I managed to execute the `setup` without `sudo` and get to the state of downloading `gitbug-java_offline_environments_1.tar.gz` archive.

 I am experiencing some troubles with extraction of this tar-archive but it might be a local problem with internet connection:
```
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Comment by Vladislav0Art** [comment] 2024-03-06 15:06
On the 107-th line of the `./gitbug-java` file there is an undefined name `act_cache`:
```
https://zenodo.org/records/10578602/files/gitbug-java_offline_environments_1.tar.gz?download=1: 100%|██████████████████| 34.3G/34.3G [15:04<00:00, 40.7MB/s]
https://zenodo.org/records/10578617/files/gitbug-java_offline_environments_2.tar.gz?download=1: 100%|██████████████████| 45.7G/45.7G [10:05<00:00, 81.1MB/s]
Traceback (most recent call last):
  File "/home/ubuntu/projects/gitbug-java/gitbug-java", line 206, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/projects/gitbug-java/gitbug-java", line 202, in main
    fire.Fire(GitBugJavaCli)
  File "/home/ubuntu/projects/gitbug-java/venv/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/gitbug-java/venv/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/gitbug-java/venv/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/gitbug-java/gitbug-java", line 195, in setup
    self.__setup_act_cache(
  File "/home/ubuntu/projects/gitbug-java/gitbug-java", line 107, in __setup_act_cache
    if not act_cache.exists():
           ^^^^^^^^^
NameError: name 'act_cache' is not defined
```

I suspect `__setup_act_cache` function might have mistakes in the implementation. Shouldn't it be as follows:
```diff
    def __setup_act_cache(self, name: str, download_url: str):
        # Download the zip
-       zip_path = Path(get_project_root(), "act-cache.zip")
+       zip_path = Path(get_project_root(), name + ".zip")
-        if not act_cache.exists():
+       if not zip_path.exists():
            self.__download(download_url, zip_path)
        # Extract the zip
-      cache_path = Path(get_project_root(), "act-cache")
+      cache_path = Path(get_project_root(), name)
        cache_path.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(zip_path, "r") as zip_ref:
            zip_ref.extractall(cache_path)
        os.remove(zip_path)
```

**Comment by andre15silva** [comment] 2024-03-06 15:40
Hi again @Vladislav0Art!

Thanks for spotting that problem with the variables, you're right! 
We must have missed those changes. #19 fixes this part of the issue.

 > Now I managed to execute the `setup` without `sudo` and get to the state of downloading `gitbug-java_offline_environments_1.tar.gz` archive.
> 
> I am experiencing some troubles with extraction of this tar-archive but it might be a local problem with internet connection:
> 
> ```
> EOFError: Compressed file ended before the end-of-stream marker was reached
> ```

For this other issue, do you know if the download was successful? Is the md5sum of the file you have locally `6d6eae507a68800a4aa1f0648860720c`?

**Comment by Vladislav0Art** [comment] 2024-03-06 16:22
Yes, the `EOFError` was related to my local connectivity issues, I redownloaded the archive and it fixed the problem.

**Comment by andre15silva** [comment] 2024-03-06 16:49
Ah, great! I am closing this issue then.

Feel free to open more issues if you find further problems :)

**Closed by andre15silva** 2024-03-06 16:49 UTC
